"""initial

Revision ID: 0001
Revises:
Create Date: 2026-05-06 05:50:48.723347+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(display_name) BETWEEN 1 AND 200", name="ck_brands_display_name_length"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("brand_id", sa.String(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("format", sa.String(length=8), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("parse_status", sa.String(length=16), nullable=False),
        sa.Column("parse_error", sa.Text(), nullable=True),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("format IN ('pdf', 'docx', 'txt', 'md')", name="ck_documents_format"),
        sa.CheckConstraint(
            "parse_status IN ('parsed', 'rejected')", name="ck_documents_parse_status"
        ),
        sa.CheckConstraint("byte_size > 0 AND byte_size <= 52428800", name="ck_documents_size"),
        sa.CheckConstraint("chunk_count >= 0", name="ck_documents_chunk_count"),
        sa.CheckConstraint(
            "length(original_filename) BETWEEN 1 AND 255", name="ck_documents_filename_length"
        ),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("brand_id", "content_hash", name="uq_documents_brand_content_hash"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(
            "ix_documents_brand_created", ["brand_id", "created_at"], unique=False
        )

    op.create_table(
        "runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("brand_id", sa.String(), nullable=False),
        sa.Column("brief", sa.Text(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("target_audience", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("current_stage", sa.String(length=16), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("retry_cap", sa.Integer(), nullable=False),
        sa.Column("critic_threshold", sa.Float(), nullable=False),
        sa.Column("failed_stage", sa.String(length=16), nullable=True),
        sa.Column("failed_reason", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "current_stage IS NULL OR current_stage IN ('research', 'retrieval', 'copy', 'image', 'critic')",
            name="ck_runs_current_stage",
        ),
        sa.CheckConstraint(
            "failed_stage IS NULL OR failed_stage IN ('research', 'retrieval', 'copy', 'image', 'critic')",
            name="ck_runs_failed_stage",
        ),
        sa.CheckConstraint(
            "platform IN ('facebook', 'instagram', 'tiktok', 'twitter', 'linkedin', 'youtube')",
            name="ck_runs_platform",
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'done', 'failed')", name="ck_runs_status"
        ),
        sa.CheckConstraint("attempt_count >= 0", name="ck_runs_attempt_count"),
        sa.CheckConstraint("critic_threshold BETWEEN 0 AND 1", name="ck_runs_critic_threshold"),
        sa.CheckConstraint("length(brief) BETWEEN 1 AND 5000", name="ck_runs_brief_length"),
        sa.CheckConstraint(
            "length(target_audience) BETWEEN 1 AND 500", name="ck_runs_audience_length"
        ),
        sa.CheckConstraint("retry_cap >= 0", name="ck_runs_retry_cap"),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index("ix_runs_brand_submitted", ["brand_id", "submitted_at"], unique=False)
        batch_op.create_index("ix_runs_status", ["status"], unique=False)

    op.create_table(
        "campaign_outputs",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("winning_attempt", sa.Integer(), nullable=False),
        sa.Column("headline", sa.Text(), nullable=False),
        sa.Column("primary_text", sa.Text(), nullable=False),
        sa.Column("cta", sa.Text(), nullable=False),
        sa.Column("image_path", sa.Text(), nullable=False),
        sa.Column("image_width", sa.Integer(), nullable=False),
        sa.Column("image_height", sa.Integer(), nullable=False),
        sa.Column("final_score_overall", sa.Float(), nullable=False),
        sa.Column("final_score_breakdown_json", sa.Text(), nullable=False),
        sa.Column("final_score_passed", sa.Integer(), nullable=False),
        sa.Column("final_score_feedback", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "final_score_overall BETWEEN 0 AND 1", name="ck_campaign_outputs_overall"
        ),
        sa.CheckConstraint("final_score_passed IN (0, 1)", name="ck_campaign_outputs_passed"),
        sa.CheckConstraint("image_height >= 1", name="ck_campaign_outputs_height"),
        sa.CheckConstraint("image_width >= 1", name="ck_campaign_outputs_width"),
        sa.CheckConstraint("winning_attempt >= 1", name="ck_campaign_outputs_winning_attempt"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "stage_traces",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("inputs_json", sa.Text(), nullable=False),
        sa.Column("outputs_json", sa.Text(), nullable=False),
        sa.Column("model_calls_json", sa.Text(), nullable=False),
        sa.Column("verdict_json", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(status <> 'degraded') OR (stage = 'research')",
            name="ck_stage_traces_degraded_only_research",
        ),
        sa.CheckConstraint(
            "stage IN ('research', 'retrieval', 'copy', 'image', 'critic')",
            name="ck_stage_traces_stage",
        ),
        sa.CheckConstraint("status IN ('ok', 'degraded', 'failed')", name="ck_stage_traces_status"),
        sa.CheckConstraint("attempt >= 1", name="ck_stage_traces_attempt"),
        sa.CheckConstraint("duration_ms >= 0", name="ck_stage_traces_duration"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "attempt", "stage", name="uq_stage_traces_run_attempt_stage"),
    )
    with op.batch_alter_table("stage_traces", schema=None) as batch_op:
        batch_op.create_index(
            "ix_stage_traces_run_attempt_stage", ["run_id", "attempt", "stage"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stage_traces", schema=None) as batch_op:
        batch_op.drop_index("ix_stage_traces_run_attempt_stage")

    op.drop_table("stage_traces")
    op.drop_table("campaign_outputs")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index("ix_runs_status")
        batch_op.drop_index("ix_runs_brand_submitted")

    op.drop_table("runs")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index("ix_documents_brand_created")

    op.drop_table("documents")
    op.drop_table("brands")
    # ### end Alembic commands ###
